export const data = {
  contacts: [
    {
      url: 'https://linkedin.com/in/up2dul',
      display: 'linkedin.com/in/up2dul',
      label: 'LinkedIn',
    },
    {
      url: 'https://up2dul.vercel.app',
      display: 'up2dul.vercel.app',
      label: 'Personal Website',
    },
    {
      url: 'https://github.com/up2dul',
      display: 'github.com/up2dul',
      label: 'GitHub',
    },
    {
      url: 'mailto:malik301002@gmail.com',
      display: 'malik301002@gmail.com',
      label: 'Email',
    },
  ],
  experiences: [
    {
      title: 'Frontend Developer',
      type: 'Full-time',
      period: 'May 2023 – Present',
      company: 'Svara',
      companyUrl: 'https://svara.id',
      location: 'Bandung',
      responsibilities: [
        'Using Figma to collaborate with UI/UX Designer and other Developers.',
        'Using GitLab to manage some organized codebase and collaborate with other Developers.',
        'Using ClickUp for the task management and collaborate with Project Managers or other Developers as well.',
        'Maintain internal dashboard app utilizes React v.15, which is help operations team to work with the dashboard.',
        'Maintain internal analytics app utilizes Next.js, Material UI, React Query, and TypeScript, which is help to provide analytics information for the company.',
        'Implement requested features and bug fixes for some other internal app and client project that mostly utilizes Next.js and TypeScript as well.',
      ],
    },
    {
      title: 'External Code Reviewer',
      type: 'Part-time',
      period: 'Apr 2023 – Present',
      company: 'Dicoding',
      companyUrl: 'https://dicoding.com',
      location: 'Remote',
      responsibilities: [
        "Reviewing, providing solutions and suggestions to student's submissions (assignments) in some courses according to the given course target.",
        'In the courses forum discussion, help answer questions and provide solutions to students from courses who have difficulties, either it is about technical or non-technical.',
      ],
    },
  ],
  educations: [
    {
      title: 'Telkom University',
      type: "Bachelor's Degree",
      degree: 'Informatics',
      period: 'Sep 2023 – Present',
      url: 'https://telkomuniversity.ac.id',
      location: 'Online Learning',
    },
    {
      title: 'SMK Media Informatika',
      type: 'Vocational High School',
      degree: 'Computer Software Engineering',
      period: 'Jul 2017 – May 2020',
      url: 'https://smkmediainformatika.sch.id',
      location: 'Jakarta',
    },
  ],
  skills: [
    ['HTML', 'CSS', 'SCSS', 'JavaScript', 'TypeScript'],
    [
      'Figma',
      'Node.js',
      'Docker',
      'Git',
      'GitHub',
      'GitLab',
      'React',
      'Next.js',
      'Vite',
      'Astro',
      'React Query',
      'Redux',
      'Zustand',
      'Tailwind',
      'Chakra UI',
      'Material UI',
      'Headless UI',
      'Mantine',
      'Radix',
      'Vitest',
      'Cypress',
    ],
  ],
  portfolios: [
    {
      title: 'Diforum',
      createdAt: 'Jan 2023',
      url: 'https://diforum.vercel.app',
      urlPreview: 'diforum.vercel.app',
      description: 'A discussion app, created as a final submission for React expert course from Dicoding.',
    },
    {
      title: 'CSS Shadow Generator',
      createdAt: 'Aug 2022',
      url: 'https://css-shadow-gen.vercel.app',
      urlPreview: 'css-shadow-gen.vercel.app',
      description: 'An app to help generate box-shadow or text-shadow CSS code with customization.',
    },
  ],
};
