export const data = {
  contacts: [
    {
      url: 'https://linkedin.com/in/up2dul',
      display: 'linkedin.com/in/up2dul',
      label: 'LinkedIn',
    },
    {
      url: 'https://up2dul.vercel.app',
      display: 'up2dul.vercel.app',
      label: 'Personal Website',
    },
    {
      url: 'https://github.com/up2dul',
      display: 'github.com/up2dul',
      label: 'GitHub',
    },
    {
      url: 'mailto:malik301002@gmail.com',
      display: 'malik301002@gmail.com',
      label: 'Email',
    },
  ],
  experiences: [
    {
      title: 'Frontend Developer',
      type: 'Full-time',
      period: 'May 2023 – Present',
      company: 'Svara',
      companyUrl: 'https://svara.id',
      location: 'Bandung',
      responsibilities: [
        'Using GitLab to manage code repositories, collaborate with other developers, and maintain organized codebase.',
        'Using ClickUp to manage projects, tasks, and collaborate with Project Managers.',
        'Implement requested features for internal dashboard app that utilize React v.15.',
        'Implement requested features and bug fixing for Data Command Center app project that utilize Next.js, Material UI, React Query, and TypeScript.',
      ],
    },
    {
      title: 'External Code Reviewer',
      type: 'Part-time',
      period: 'Apr 2023 – Present',
      company: 'Dicoding',
      companyUrl: 'https://dicoding.com',
      location: 'Remote',
      responsibilities: [
        "Reviewing student's submission (assignment) in a course according to the given target.",
        "Provide solution and suggestion to student's submission.",
        'Help to answer the forum discussion.',
      ],
    },
  ],
  educations: [
    {
      title: 'Telkom University',
      type: "Bachelor's Degree",
      degree: 'Informatics',
      period: 'Sep 2023 – Present',
      url: 'https://telkomuniversity.ac.id',
      location: 'Online Learning',
    },
    {
      title: 'SMK Media Informatika',
      type: 'Vocational High School',
      degree: 'Computer Software Engineering',
      period: 'Jul 2017 – May 2020',
      url: 'https://smkmediainformatika.sch.id',
      location: 'Jakarta',
    },
  ],
  skills: [
    ['Markdown', 'HTML', 'CSS', 'SCSS', 'JavaScript', 'TypeScript', 'Node.js'],
    [
      'Figma',
      'Git',
      'React',
      'Next.js',
      'React Query',
      'Astro',
      'Redux',
      'Zustand',
      'Tailwind',
      'Chakra UI',
      'Material UI',
      'Headless UI',
      'Mantine',
      'Radix',
    ],
  ],
  portfolios: [
    {
      title: 'Diforum',
      createdAt: 'Jan 2023',
      url: 'https://diforum.vercel.app',
      urlPreview: 'diforum.vercel.app',
      description: 'A discussion app, created as a final submission for React expert course from Dicoding.',
    },
    {
      title: 'CSS Shadow Generator',
      createdAt: 'Aug 2022',
      url: 'https://css-shadow-gen.vercel.app',
      urlPreview: 'css-shadow-gen.vercel.app',
      description: 'An app to help generate box-shadow or text-shadow CSS code with customization.',
    },
  ],
};
